<li  class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2739 {{ Request::is('boston-new-york-moving-prices') ?"current-menu-item" : ""}} one-page-link"><a href="/boston-new-york-moving-prices">Boston to New York, NY</a></li>
<li  class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2740 {{ Request::is('boston-chicago-moving') ?"current-menu-item" : ""}} one-page-link"><a href="/boston-chicago-moving">Boston to Chicago, IL</a></li>
<li  class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2741 {{ Request::is('boston-to-philadelphia-moving') ?"current-menu-item" : ""}} one-page-link"><a href="/boston-to-philadelphia-moving">Boston to Philadelphia, PA</a></li>
<li  class="menu-item menu-item-type-post_type menu-item-object-page page-item-2482 {{ Request::is('boston-to-washington-dc-moving') ?"current-menu-item" : ""}} one-page-link"><a href="/boston-to-washington-dc-moving">Boston to Washington, DC</a></li>
<li  class="menu-item menu-item-type-post_type menu-item-object-page page-item-2482 {{ Request::is('boston-to-florida-moving') ?"current-menu-item" : ""}} one-page-link"><a href="/boston-to-florida-moving">Boston to Florida</a></li>
<li  class="menu-item menu-item-type-post_type menu-item-object-page page-item-2482 {{ Request::is('boston-to-ohio-moving') ?"current-menu-item" : ""}} one-page-link"><a href="/boston-to-ohio-moving">Boston to Ohio</a></li>
<li  class="menu-item menu-item-type-post_type menu-item-object-page page-item-2482 one-page-link {{ Request::is('boston-losangeles-moving') ?"active" : ""}}"><a href="/boston-losangeles-moving">Boston to Los Angeles, CA</a></li>
<li  class="menu-item menu-item-type-post_type menu-item-object-page page-item-2482 one-page-link {{ Request::is('boston-miami-moving') ?"active" : ""}}"><a href="/boston-miami-moving">Boston to Miami, FL</a></li>
<li  class="menu-item menu-item-type-post_type menu-item-object-page page-item-2482 one-page-link {{ Request::is('boston-charlotte-moving') ?"active" : ""}}"><a href="/boston-charlotte-moving">Boston to Charlotte, NC</a></li>
<li  class="menu-item menu-item-type-post_type menu-item-object-page page-item-2482 one-page-link {{ Request::is('boston-houston-moving') ?"active" : ""}}"><a href="/boston-houston-moving">Boston to Houston, TX</a></li>
